# Предложения
## Получить список предложений
GET http://localhost:3000/offers HTTP/1.1
Content-Type: application/json

###

## Получить список премиум предложений по городу
GET http://localhost:3000/offers/premium/amsterdam HTTP/1.1
Content-Type: application/json

###

##  Получить одно предложение
GET http://localhost:3000/offers/65ca01e9ab9ff00e6139d826 HTTP/1.1
Content-Type: application/json

###

##  Добавить/удалить предложение в избранное
PATCH http://localhost:3000/offers/favorites/65ca01e9ab9ff00e6139d833 HTTP/1.1
Content-Type: application/json

###

## Создать новое предложение
POST http://localhost:3000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Уютная квартира в центре Парижа",
  "description": "Прекрасная квартира с видом на исторические достопримечательности города.",
  "publicationDate": "2023-12-15T08:00:00.000Z",
  "city": "Paris",
  "previewImage": "https://example.com/images/paris-apartment.jpg",
  "propertyPhotos": [
    "https://example.com/images/paris-apartment-1.jpg",
    "https://example.com/images/paris-apartment-2.jpg",
    "https://example.com/images/paris-apartment-3.jpg"
  ],
  "premium": true,
  "rating": 4.5,
  "objectType": "Apartment",
  "numberOfRooms": 2,
  "numberOfGuests": 4,
  "rentalCost": 120,
  "amenities": ["Air conditioning", "Laptop friendly workspace", "Towels"],
  "author": "65ca01e9ab9ff00e6139d81e",
  "locationCoordinates": { "latitude": 48.8566, "longitude": 2.3522 }
}

###

##  Обновить предложение
PATCH http://localhost:3000/offers/65df946e0f4ac40134ac1474 HTTP/1.1
Content-Type: application/json

{
  "description": "Очень уютная квартира в историческом центре города"
}

###

##  Удалить предложение
DELETE http://localhost:3000/offers/65df96e2e359288270461a53 HTTP/1.1
Content-Type: application/json

###

